### ISSUE TITLE
xmpp adapter

### ISSUE THREAD

**Issue by richp10** [oklahomer/go-sarah#53]
Is there an xmpp adapter for sarah - I can't see one. 

Writing one would probably be a little beyond my current competence with go but I may have a go OR (more likely) pay a bounty for this. @oklahomer would you be interested?

I assume the task would involved taking the /slack folder and creating an /xmpp package with the same api but using an xmpp library rather than golack - so we then just use the adapter like snippet below - but everything else in Sarah would work the same as with the slack adapter. Do I understand this correctly? 

```
func setupXmpp(config *slack.Config, storage sarah.UserContextStorage) (sarah.Bot, error) {
	adapter, err := xmpp.NewAdapter(config)
	if err != nil {
		return nil, err
	}

	return sarah.NewBot(adapter, sarah.BotWithStorage(storage))
}
```

**Comment by oklahomer** [comment]
Thank you for raising this issue, @richp10.

Yes, that is one way to provide XMPP adapter for this project. However I would create a separate repository for that particular protocol just like [`go-sarah-line`](https://github.com/oklahomer/go-sarah-line) because this new XMPP adapter creates additional dependency for a third-party library. Slack adapter you mentioned indeed has [a dependency](https://github.com/oklahomer/golack) so I am actually thinking to create a separate repository for Slack integration. The reason why I have Slack integration in this repository now is that my old [Python implementation of sarah](https://github.com/oklahomer/sarah) supports Slack out of the box.

With that said, I am interested in providing XMPP integration. I would create a `sarah.Adapter` implementation for XMPP and host it under `github.com/oklahomer/go-sarah-xmpp`. Just to be clear, are you trying to integrate with any particular XMPP-oriented chat service like HipChat? XMPP's spec is pretty huge and each chat service has own flavored implementation, so I just got interested.

And again, thank you for raising this valuable issue, @richp10. You are the first developer who raised an issue other than the author myself.

**Comment by richp10** [comment]
Hi there thanks for the fast response (and great project..)

I need 'vanilla' xmpp - idealy both MUC and one to one messaging.  The core of the XMPP spec is pretty stable and the vast majority of extensions are not needed for sarah type bots - as far as I can see.  I use ejabberd personally - but any xmpp server (rather than hipchat etc) is the target. 

I am fairly new to Go and landing this might be a bit beyond my reach - though I have already made a start and am happy to share progress.  I propose creating a github repo (MIT) with what I have done.. and maybe you want to fix / finish it - or start again I am not sure!  My need is not urgent - but I kind of need it within weeks not months and might be happy to pay a bounty on this if it would help you get to this!

Thoughts..

**Comment by richp10** [comment]
Or why don't you create github oklahoma/go-sarah-xmpp now - I will fork that and commit what I have done to there and PR in.. won't be working but I hope a start.

**Comment by oklahomer** [comment]
Currently I am in between holidays and will be able to spend some time on this from tomorrow. So I will just create the repository at `github.com/oklahomer/go-sarah-xmpp` and build the basic structures.

As far as I can see, using [https://github.com/mattn/go-xmpp](mattn/go-xmpp) seems a good starting point to build this new `sarah.Adapter`. The [godoc](https://godoc.org/github.com/mattn/go-xmpp) says this library is for Google Talk, but actually supports both [RFC 3920](https://tools.ietf.org/html/rfc3920) and [RFC 3921](https://tools.ietf.org/html/rfc3921). Some XEPs including the one for MUC is also supported so this covers your needs I suppose.

**Comment by richp10** [comment]
Yes please, create the repo; I am maybe 50% there in terms of high level functionality - so code to create, run and monitor the xmpp connection, and passing incoming messages to sarah. I have followed the API and structure of the line and slack adapters. I will sketch the Sendmessage method today.  At that point absolutely *nothing* will work and I will hand over to you :)

Hopefully you will mostly need to debug rather than dig into xmpp. 

Yes, I used /mattn/go-xmpp - which seems to be still maintained.  Though originally for google talk, google talk no longer supports xmpp so I am pretty certain the library is now a generic xmpp library. So far it looks a good fit - though possible a fork and tweak will be needed (it *might* not expose all the message details we need). 

Being very new to Go - I do not yet have a strong understanding of channels and I _think_ some of the use of channels in the slack adapter will not be needed with the xmpp adapter. xmpp needs one and only one connection and needs to simply pass messages into sarah. I don't _think_ this adapter needs its own messageQueue because the queue is handled by xmpp.  Unless I am confused, the xmpp adapter should be simpler.. closer to the Line adapter (which I should have used as my starting point :)

I will work on this today - let me know when the repo is up and I will fork and do a PR.. *possible* that it will be a quick job for you to tweak and debug but lets see.

**Comment by richp10** [comment]
I suggest an empty repo - I have the basic structures already..

**Comment by oklahomer** [comment]
Here you go, @richp10 
https://github.com/oklahomer/go-sarah-xmpp

**Comment by richp10** [comment]
Thanks - I will push a hopefully helpful fiasco in about an hour!

**Comment by richp10** [comment]
Pushed first commit - lets discuss on my PR / issues in that repo..
