### ISSUE TITLE
Mattermost Adapter

### ISSUE THREAD

**Issue by jselleck** [oklahomer/go-sarah#65]
Create Mattermost adapter so that the project can be used on premises with Mattermost.  

This may be easy through an adaption of existing go-mattermost integrations.  

i.e. https://github.com/mattermost/mattermost-bot-sample-golang

**Comment by oklahomer** [comment]
Thank you for contributing to this project, @jselleck! I am always happy to see people having interests in my work. Also I liked the idea of Mattermost adapter considering the number of its users.

Currently there are several adapters for `go-sarah` including Slack, Gitter, XMPP and LINE as listed at https://github.com/oklahomer/go-sarah#supported-chat-servicesprotocols . Gitter and Slack are developed and maintained in this repository while others are located in other repositories.

Basically I prefer to have adapter implementations managed in other repositories to avoid having extra dependencies. GItter and Slack adapters are hosted in this repository because I needed some reference implementations. Gitter adapter only required standard libraries so this was an ideal reference implementation. Slack adapter required some non-standard library to handle WebSocket integration so I am even thinking to separate it from this repository.

With that said, I would prefer to have Mattermost adapter hosted and maintained as a separate project. Would you like to host and develop by yourself or do you need a help?

**Comment by oklahomer** [comment]
@jselleck What do you think?
I'll be closing this issue in a week if I don't get any response from you.

**Comment by jselleck** [comment]
Thanks @oklahomer .  We’re still evaluating our approach so the need has not been finalized.  If we write an adapter we’ll try to release it.   You can close the issue.  Thanks!!!

**Comment by oklahomer** [comment]
Appreciate your quick response.
I'm closing this issue for now, but let me know when you need a help :)
